import React, { useEffect, useMemo, useState } from 'react';
import { ExternalLink, Loader2, Plus, Save, Trash2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Label } from '@/components/ui/label';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';

const scalarKeys = [
  'wpistic_accent_word','wpistic_subtitle','wpistic_short_summary','wpistic_duration','wpistic_start_location','wpistic_end_location',
  'wpistic_group_size','wpistic_minimum_age','wpistic_season','wpistic_accommodation','wpistic_transport','wpistic_availability',
  'wpistic_departures_label','wpistic_from_price','wpistic_pricing_type','wpistic_deposit_type','wpistic_deposit_value','wpistic_deposit_min','wpistic_deposit_max',
];
const emptyMeta=Object.fromEntries(scalarKeys.map(k=>[k,'']));

function stateFromTour(tour={}) {
  const meta={...emptyMeta,...(tour.meta||{})};
  return {
    title:tour.title||'', slug:tour.slug||'', status:tour.status||'draft', content:tour.content||'', excerpt:tour.excerpt||'',
    featuredMedia:tour.featuredMedia||0,
    meta:{
      ...meta,
      wpistic_itinerary:Array.isArray(meta.wpistic_itinerary)?meta.wpistic_itinerary:[],
      wpistic_faq:Array.isArray(meta.wpistic_faq)?meta.wpistic_faq:[],
      wpistic_inclusions:Array.isArray(meta.wpistic_inclusions)?meta.wpistic_inclusions:[],
      wpistic_exclusions:Array.isArray(meta.wpistic_exclusions)?meta.wpistic_exclusions:[],
    },
  };
}

export default function TourEditor({tour,mode='edit',saving=false,saveError,onSave,onCancel,onDelete}) {
  const initial=useMemo(()=>stateFromTour(tour),[tour]);
  const [form,setForm]=useState(initial); const [errors,setErrors]=useState({});
  useEffect(()=>setForm(initial),[initial]);
  const dirty=JSON.stringify(form)!==JSON.stringify(initial);
  useEffect(()=>{if(!dirty)return;const h=(e)=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',h);return()=>window.removeEventListener('beforeunload',h);},[dirty]);
  const setTop=(k,v)=>setForm(f=>({...f,[k]:v}));
  const setMeta=(k,v)=>setForm(f=>({...f,meta:{...f.meta,[k]:v}}));
  const validate=()=>{const e={};if(!form.title.trim())e.title='Title is required.';if(form.slug&&!/^[a-z0-9-]+$/.test(form.slug))e.slug='Use lowercase letters, numbers and hyphens.';setErrors(e);return !Object.keys(e).length;};
  const submit=(status)=>{if(!validate())return;const payload={...form,status:status||form.status,featuredMedia:Number(form.featuredMedia)||0};onSave(payload);};
  const taxonomies=tour?.taxonomies||{};
  return <div className="space-y-4">
    <div className="sticky top-[68px] z-20 rounded-xl border border-border bg-card/95 p-3 backdrop-blur">
      <div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm font-semibold">{mode==='create'?'New tour':form.title||'Edit tour'}</p><p className="text-xs text-muted-foreground">{saving?'Saving…':dirty?'Unsaved changes':'All changes saved'}</p></div><div className="flex flex-wrap gap-2">{tour?.permalink&&<a href={tour.permalink} target="_blank" rel="noreferrer" className="inline-flex h-9 items-center gap-1.5 rounded-lg border border-border px-3 text-sm"><ExternalLink className="h-4 w-4"/>Preview</a>}{mode==='edit'&&onDelete&&<Button variant="outline" size="sm" className="h-9 text-destructive" onClick={onDelete}><Trash2 className="mr-1 h-4 w-4"/>Delete</Button>}<Button variant="ghost" size="sm" className="h-9" onClick={onCancel}>Cancel</Button>{form.status!=='publish'&&<Button variant="outline" size="sm" className="h-9" disabled={saving} onClick={()=>submit('publish')}>Publish</Button>}<Button size="sm" className="h-9" disabled={saving||(!dirty&&mode==='edit')} onClick={()=>submit()}>{saving?<Loader2 className="mr-1 h-4 w-4 animate-spin"/>:<Save className="mr-1 h-4 w-4"/>}{mode==='create'?'Create':'Save'}</Button></div></div>
      {saveError&&<p className="mt-2 rounded-lg border border-destructive/30 bg-destructive/10 px-3 py-2 text-sm text-destructive">{saveError.message||'Save failed. Your changes are still in the form.'}</p>}
    </div>
    <Tabs defaultValue="overview">
      <TabsList className="mb-4 flex h-10 w-full justify-start overflow-x-auto"><TabsTrigger value="overview">Overview</TabsTrigger><TabsTrigger value="details">Details</TabsTrigger><TabsTrigger value="pricing">Pricing</TabsTrigger><TabsTrigger value="itinerary">Itinerary</TabsTrigger><TabsTrigger value="content">Included / FAQ</TabsTrigger></TabsList>
      <TabsContent value="overview"><Panel title="Overview"><div className="grid gap-4 sm:grid-cols-2"><Field label="Title" required value={form.title} onChange={v=>setTop('title',v)} error={errors.title} wide/><Field label="Slug" value={form.slug} onChange={v=>setTop('slug',v)} error={errors.slug}/><label className="grid gap-2 text-xs text-muted-foreground"><span>Status</span><select className="h-10 rounded-lg border border-input bg-background px-3 text-sm text-foreground" value={form.status} onChange={e=>setTop('status',e.target.value)}>{['draft','publish','pending','private','future'].map(v=><option key={v} value={v}>{v==='publish'?'Published':cap(v)}</option>)}</select></label><Field label="Featured media attachment ID" type="number" value={form.featuredMedia} onChange={v=>setTop('featuredMedia',v)}/></div>{tour?.featuredImage&&<img src={tour.featuredImage} alt="" className="mt-4 h-44 w-full max-w-lg rounded-lg border border-border object-cover"/>}<Area label="Excerpt" rows={3} value={form.excerpt} onChange={v=>setTop('excerpt',v)}/><Area label="Main content" rows={12} value={form.content} onChange={v=>setTop('content',v)}/></Panel></TabsContent>
      <TabsContent value="details"><Panel title="Tour details"><div className="grid gap-4 sm:grid-cols-2"><Field label="Subtitle" value={form.meta.wpistic_subtitle} onChange={v=>setMeta('wpistic_subtitle',v)} wide/><Area label="Short summary" rows={3} value={form.meta.wpistic_short_summary} onChange={v=>setMeta('wpistic_short_summary',v)} wide/><Field label="Accent word" value={form.meta.wpistic_accent_word} onChange={v=>setMeta('wpistic_accent_word',v)}/><Field label="Duration" value={form.meta.wpistic_duration} onChange={v=>setMeta('wpistic_duration',v)}/><Field label="Start location" value={form.meta.wpistic_start_location} onChange={v=>setMeta('wpistic_start_location',v)}/><Field label="End location" value={form.meta.wpistic_end_location} onChange={v=>setMeta('wpistic_end_location',v)}/><Field label="Group size" value={form.meta.wpistic_group_size} onChange={v=>setMeta('wpistic_group_size',v)}/><Field label="Minimum age" value={form.meta.wpistic_minimum_age} onChange={v=>setMeta('wpistic_minimum_age',v)}/><Field label="Season" value={form.meta.wpistic_season} onChange={v=>setMeta('wpistic_season',v)}/><Field label="Accommodation" value={form.meta.wpistic_accommodation} onChange={v=>setMeta('wpistic_accommodation',v)}/><Field label="Transport" value={form.meta.wpistic_transport} onChange={v=>setMeta('wpistic_transport',v)}/><Field label="Availability text" value={form.meta.wpistic_availability} onChange={v=>setMeta('wpistic_availability',v)}/><Field label="Departures label" value={form.meta.wpistic_departures_label} onChange={v=>setMeta('wpistic_departures_label',v)}/></div><TaxonomySummary taxonomies={taxonomies}/></Panel></TabsContent>
      <TabsContent value="pricing"><Panel title="Pricing & deposit"><div className="grid gap-4 sm:grid-cols-2"><Field label="From price" value={form.meta.wpistic_from_price} onChange={v=>setMeta('wpistic_from_price',v)}/><label className="grid gap-2 text-xs text-muted-foreground"><span>Pricing type</span><select className="h-10 rounded-lg border border-input bg-background px-3 text-sm text-foreground" value={form.meta.wpistic_pricing_type||'request'} onChange={e=>setMeta('wpistic_pricing_type',e.target.value)}>{['request','starting','person','group'].map(v=><option key={v} value={v}>{cap(v)}</option>)}</select></label><label className="grid gap-2 text-xs text-muted-foreground"><span>Deposit type</span><select className="h-10 rounded-lg border border-input bg-background px-3 text-sm text-foreground" value={form.meta.wpistic_deposit_type||''} onChange={e=>setMeta('wpistic_deposit_type',e.target.value)}><option value="">None</option><option value="fixed">Fixed</option><option value="percent">Percent</option></select></label><Field label="Deposit value" value={form.meta.wpistic_deposit_value} onChange={v=>setMeta('wpistic_deposit_value',v)}/><Field label="Deposit minimum" value={form.meta.wpistic_deposit_min} onChange={v=>setMeta('wpistic_deposit_min',v)}/><Field label="Deposit maximum" value={form.meta.wpistic_deposit_max} onChange={v=>setMeta('wpistic_deposit_max',v)}/></div></Panel></TabsContent>
      <TabsContent value="itinerary"><Panel title="Itinerary"><Repeater rows={form.meta.wpistic_itinerary} onChange={v=>setMeta('wpistic_itinerary',v)} fields={[['title','Title'],['body','Description']]} addLabel="Add itinerary item"/></Panel></TabsContent>
      <TabsContent value="content"><div className="grid gap-4 xl:grid-cols-2"><Panel title="Inclusions"><LineList values={form.meta.wpistic_inclusions} onChange={v=>setMeta('wpistic_inclusions',v)} placeholder="Included item"/></Panel><Panel title="Exclusions"><LineList values={form.meta.wpistic_exclusions} onChange={v=>setMeta('wpistic_exclusions',v)} placeholder="Excluded item"/></Panel></div><div className="mt-4"><Panel title="Frequently asked questions"><Repeater rows={form.meta.wpistic_faq} onChange={v=>setMeta('wpistic_faq',v)} fields={[['q','Question'],['a','Answer']]} addLabel="Add question"/></Panel></div></TabsContent>
    </Tabs>
  </div>;
}

function Panel({title,children}){return <section className="rounded-xl border border-border bg-card p-5"><h3 className="mb-4 text-sm font-semibold">{title}</h3>{children}</section>}
function Field({label,value,onChange,error,required,wide,type='text'}){return <label className={`grid gap-2 text-xs text-muted-foreground ${wide?'sm:col-span-2':''}`}><span>{label}{required&&<b className="text-destructive"> *</b>}</span><Input type={type} className="h-10 text-sm text-foreground" value={value??''} onChange={e=>onChange(e.target.value)}/>{error&&<span className="text-destructive">{error}</span>}</label>}
function Area({label,value,onChange,rows=4,wide=false}){return <label className={`mt-4 grid gap-2 text-xs text-muted-foreground ${wide?'sm:col-span-2':''}`}><span>{label}</span><Textarea rows={rows} className="text-sm text-foreground" value={value??''} onChange={e=>onChange(e.target.value)}/></label>}
function Repeater({rows,onChange,fields,addLabel}){return <div className="space-y-3">{rows.map((row,i)=><div key={i} className="rounded-lg border border-border p-3"><div className="mb-2 flex justify-end"><button type="button" onClick={()=>onChange(rows.filter((_,x)=>x!==i))} className="text-xs text-destructive">Remove</button></div>{fields.map(([key,label])=>key==='body'||key==='a'?<Area key={key} label={label} rows={3} value={row[key]||''} onChange={v=>onChange(rows.map((r,x)=>x===i?{...r,[key]:v}:r))}/>:<Field key={key} label={label} value={row[key]||''} onChange={v=>onChange(rows.map((r,x)=>x===i?{...r,[key]:v}:r))}/>)}</div>)}<Button variant="outline" size="sm" onClick={()=>onChange([...rows,Object.fromEntries(fields.map(([k])=>[k,'']))])}><Plus className="mr-1 h-4 w-4"/>{addLabel}</Button></div>}
function LineList({values,onChange,placeholder}){return <div className="space-y-2">{values.map((v,i)=><div key={i} className="flex gap-2"><Input value={v} placeholder={placeholder} onChange={e=>onChange(values.map((x,n)=>n===i?e.target.value:x))}/><button type="button" onClick={()=>onChange(values.filter((_,n)=>n!==i))} className="rounded-lg px-2 text-destructive"><Trash2 className="h-4 w-4"/></button></div>)}<Button variant="outline" size="sm" onClick={()=>onChange([...values,''])}><Plus className="mr-1 h-4 w-4"/>Add</Button></div>}
function TaxonomySummary({taxonomies}){const rows=Object.entries(taxonomies||{}).filter(([,terms])=>Array.isArray(terms)&&terms.length);if(!rows.length)return null;return <div className="mt-5 border-t border-border pt-4"><p className="mb-2 text-xs font-medium uppercase tracking-wide text-muted-foreground">Current taxonomies</p><div className="space-y-2">{rows.map(([tax,terms])=><div key={tax} className="text-sm"><span className="text-muted-foreground">{cap(tax.replace(/_/g,' '))}: </span>{terms.map(t=>t.name).join(', ')}</div>)}</div><p className="mt-2 text-xs text-muted-foreground">Taxonomy assignment is read-only here until the API exposes a term catalogue.</p></div>}
function cap(v){return String(v||'').replace(/_/g,' ').replace(/\b\w/g,m=>m.toUpperCase())}
