import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { Helmet } from 'react-helmet';
import { AlertTriangle, CheckCircle2, Network, Plus, RefreshCw, Trash2 } from 'lucide-react';
import { createConnection, deleteConnection, listConnectionLogs, listConnections, updateConnection } from '@/api/connections';
import { ApiError } from '@/api/client';
import { ErrorState, Skeleton, UnavailableState } from '@/components/states/StateViews';
import { formatDate } from '@/lib/format';
import { useAuth } from '@/context/AuthContext';

const emptyForm = { name:'', targetUrl:'', secret:'', events:[], enabled:true };

export default function ConnectionsPage(){
 const {user}=useAuth(); const canAdmin=(user?.roles||[]).includes('administrator');
 const [state,setState]=useState('LOADING');const [data,setData]=useState(null);const [logs,setLogs]=useState([]);const [error,setError]=useState(null);const [form,setForm]=useState(emptyForm);const [editing,setEditing]=useState(null);const [saving,setSaving]=useState(false);const [notice,setNotice]=useState('');
 const load=useCallback(async()=>{setState('LOADING');setError(null);try{const [connections,logPage]=await Promise.all([listConnections(),listConnectionLogs({perPage:30}).catch(()=>({items:[]}))]);setData(connections);setLogs(logPage?.items||[]);setState('DATA');}catch(err){setError(err);setState(err instanceof ApiError&&err.isUnavailable?'UNAVAILABLE':'ERROR');}},[]);useEffect(()=>{load();},[load]);
 const events=data?.supportedEvents||[];const items=data?.items||[];const failureCount=useMemo(()=>logs.filter(l=>!l.success).length,[logs]);
 function edit(item){setEditing(item.id);setForm({name:item.name||'',targetUrl:item.targetUrl||'',secret:'',events:item.events||[],enabled:Boolean(item.enabled)});setNotice('');}
 function reset(){setEditing(null);setForm(emptyForm);}
 async function save(e){e.preventDefault();setSaving(true);setNotice('');try{const payload={name:form.name.trim(),targetUrl:form.targetUrl.trim(),events:form.events,enabled:form.enabled};if(form.secret)payload.secret=form.secret;if(editing)await updateConnection(editing,payload);else await createConnection({...payload,secret:form.secret});setNotice(editing?'Connection updated.':'Connection created.');reset();await load();}catch(err){setNotice(err?.message||'Could not save connection.');}finally{setSaving(false);}}
 async function remove(id){if(!window.confirm('Delete this connection? Existing delivery logs may remain for audit purposes.'))return;try{await deleteConnection(id);await load();}catch(err){setNotice(err?.message||'Could not delete connection.');}}
 function toggleEvent(event){setForm(f=>({...f,events:f.events.includes(event)?f.events.filter(x=>x!==event):[...f.events,event]}));}
 return <><Helmet><title>Connections · Brother Tours Operations</title><meta name="robots" content="noindex,nofollow"/></Helmet><div className="space-y-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-xl font-semibold">Connections</h1><p className="mt-1 text-sm text-muted-foreground">Manage outbound integrations and review recent delivery health. Secrets are never displayed.</p></div><button onClick={load} className="inline-flex h-9 items-center gap-2 rounded-lg border border-border px-3 text-sm"><RefreshCw className="h-4 w-4"/>Refresh</button></div>
 {state==='LOADING'&&<div className="grid gap-4 md:grid-cols-2">{Array.from({length:4}).map((_,i)=><Skeleton key={i} className="h-36 rounded-xl"/>)}</div>}{state==='UNAVAILABLE'&&<UnavailableState error={error} onRetry={load}/>} {state==='ERROR'&&<ErrorState error={error} onRetry={load}/>} {state==='DATA'&&<><div className="grid gap-4 md:grid-cols-3"><div className="rounded-xl border border-border bg-card p-5"><Network className="h-5 w-5 text-primary"/><p className="mt-3 text-2xl font-semibold">{items.length}</p><p className="text-xs text-muted-foreground">Configured connections</p></div><div className="rounded-xl border border-border bg-card p-5"><CheckCircle2 className="h-5 w-5 text-emerald-600"/><p className="mt-3 text-2xl font-semibold">{items.filter(i=>i.enabled).length}</p><p className="text-xs text-muted-foreground">Enabled</p></div><div className="rounded-xl border border-border bg-card p-5"><AlertTriangle className="h-5 w-5 text-amber-600"/><p className="mt-3 text-2xl font-semibold">{failureCount}</p><p className="text-xs text-muted-foreground">Failures in recent log page</p></div></div>
 <div className="grid gap-5 xl:grid-cols-[1.3fr_.7fr]"><div className="space-y-4">{items.length===0?<div className="rounded-xl border border-dashed border-border bg-card p-8 text-center text-sm text-muted-foreground">No connections configured.</div>:items.map(item=><div key={item.id} className="rounded-xl border border-border bg-card p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><h2 className="font-semibold">{item.name}</h2><span className={`rounded-full px-2 py-0.5 text-xs ${item.enabled?'bg-emerald-500/10 text-emerald-700 dark:text-emerald-400':'bg-secondary text-muted-foreground'}`}>{item.enabled?'Enabled':'Disabled'}</span></div><p className="mt-1 break-all text-xs text-muted-foreground">{item.targetUrl}</p><p className="mt-2 text-xs text-muted-foreground">{item.type || 'webhook'} · Secret {item.hasSecret?'configured':'not configured'}</p></div>{canAdmin&&<div className="flex gap-2"><button onClick={()=>edit(item)} className="rounded-lg border border-border px-3 py-2 text-xs font-medium">Edit</button><button onClick={()=>remove(item.id)} aria-label={`Delete ${item.name}`} className="rounded-lg border border-destructive/30 p-2 text-destructive"><Trash2 className="h-4 w-4"/></button></div>}</div><div className="mt-3 flex flex-wrap gap-1.5">{(item.events||[]).map(ev=><span key={ev} className="rounded-md bg-secondary px-2 py-1 text-[11px] text-muted-foreground">{ev}</span>)}</div></div>)}</div>
 <div>{canAdmin?<form onSubmit={save} className="sticky top-24 space-y-4 rounded-xl border border-border bg-card p-5"><div className="flex items-center gap-2"><Plus className="h-4 w-4"/><h2 className="font-semibold">{editing?'Edit connection':'New connection'}</h2></div><input required className="h-10 w-full rounded-lg border border-input bg-background px-3 text-sm" placeholder="Connection name" value={form.name} onChange={e=>setForm(f=>({...f,name:e.target.value}))}/><input required type="url" className="h-10 w-full rounded-lg border border-input bg-background px-3 text-sm" placeholder="https://..." value={form.targetUrl} onChange={e=>setForm(f=>({...f,targetUrl:e.target.value}))}/><input required={!editing} minLength={editing?0:16} type="password" className="h-10 w-full rounded-lg border border-input bg-background px-3 text-sm" placeholder={editing?'New secret (leave blank to keep current)':'Secret, minimum 16 characters'} value={form.secret} onChange={e=>setForm(f=>({...f,secret:e.target.value}))}/><div><p className="mb-2 text-xs font-medium text-muted-foreground">Events</p><div className="space-y-2">{events.map(ev=><label key={ev} className="flex items-center gap-2 text-xs"><input type="checkbox" checked={form.events.includes(ev)} onChange={()=>toggleEvent(ev)}/>{ev}</label>)}</div></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.enabled} onChange={e=>setForm(f=>({...f,enabled:e.target.checked}))}/>Enabled</label>{notice&&<p className="text-xs text-muted-foreground">{notice}</p>}<div className="flex gap-2"><button disabled={saving} className="h-10 flex-1 rounded-lg bg-primary px-3 text-sm font-semibold text-primary-foreground disabled:opacity-50">{saving?'Saving…':editing?'Save changes':'Create'}</button>{editing&&<button type="button" onClick={reset} className="h-10 rounded-lg border border-border px-3 text-sm">Cancel</button>}</div></form>:<div className="rounded-xl border border-border bg-card p-5 text-sm text-muted-foreground">Connection changes require an administrator account. You can still review connection status and logs.</div>}</div></div>
 <section className="rounded-xl border border-border bg-card"><div className="border-b border-border px-5 py-4"><h2 className="font-semibold">Recent delivery log</h2></div><div className="divide-y divide-border">{logs.length===0?<p className="p-5 text-sm text-muted-foreground">No recent deliveries.</p>:logs.map(log=><div key={log.id} className="grid gap-2 px-5 py-3 text-xs sm:grid-cols-[1.3fr_1fr_90px_90px_150px]"><span className="font-medium">{log.event}</span><span className="text-muted-foreground">Connection #{log.connectionId}</span><span className={log.success?'text-emerald-600':'text-destructive'}>{log.success?'Success':'Failed'}</span><span className="text-muted-foreground">HTTP {log.statusCode||'—'}</span><span className="text-muted-foreground">{formatDate(log.createdAt,{month:'short',day:'numeric',year:'numeric'})}</span></div>)}</div></section></>}
 </div></>;
}
