import React,{useCallback,useEffect,useState} from 'react';
import {Helmet} from 'react-helmet-async';
import {CalendarRange,Pencil,Plus,Trash2} from 'lucide-react';
import {createDeparture,deleteDeparture,listDepartures,updateDeparture} from '@/api/departures';
import {fetchTours} from '@/api/tours';
import {ApiError} from '@/api/client';
import {EmptyState,ErrorState,Skeleton,UnavailableState} from '@/components/states/StateViews';
import {Dialog,DialogContent,DialogDescription,DialogFooter,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import InquiryStatusBadge from '@/components/inquiries/InquiryStatusBadge';
import {formatDate} from '@/lib/format';

const blank={title:'',tourId:'',date:'',seatsTotal:0,seatsLeft:0,status:'open'};
export default function DeparturesPage(){
 const [filters,setFilters]=useState({status:'',tourId:'',from:'',to:'',page:1,perPage:50});const [state,setState]=useState('LOADING');const [data,setData]=useState(null);const [tours,setTours]=useState([]);const [error,setError]=useState(null);const [editor,setEditor]=useState(null);const [form,setForm]=useState(blank);const [saving,setSaving]=useState(false);const [formError,setFormError]=useState('');
 const load=useCallback(async()=>{setState('LOADING');setError(null);try{const [r,t]=await Promise.all([listDepartures(filters),fetchTours({perPage:100,orderby:'title',order:'ASC'}).catch(()=>({items:[]}))]);setData(r);setTours(t.items||[]);setState((r?.items||[]).length?'DATA':'EMPTY');}catch(err){setError(err);setState(err instanceof ApiError&&err.isUnavailable?'UNAVAILABLE':'ERROR');}},[filters]);useEffect(()=>{load();},[load]);
 const open=(item=null)=>{setEditor(item||{});setForm(item?{title:item.title||'',tourId:item.tourId||'',date:item.date||'',seatsTotal:item.seatsTotal??0,seatsLeft:item.seatsLeft??0,status:item.status||'open'}:blank);setFormError('');};
 const save=async()=>{if(!Number(form.tourId)||!form.date){setFormError('Tour and departure date are required.');return;}const payload={...form,tourId:Number(form.tourId),seatsTotal:Math.max(0,Number(form.seatsTotal)||0),seatsLeft:Math.max(0,Number(form.seatsLeft)||0)};if(payload.seatsLeft>payload.seatsTotal){setFormError('Seats left cannot exceed total seats.');return;}setSaving(true);setFormError('');try{editor?.id?await updateDeparture(editor.id,payload):await createDeparture(payload);setEditor(null);await load();}catch(err){setFormError(err?.message||'Save failed.');}finally{setSaving(false);}};
 const remove=async(item)=>{if(!window.confirm(`Delete departure “${item.title}”? This is blocked automatically if linked bookings exist.`))return;try{await deleteDeparture(item.id);await load();}catch(err){window.alert(err?.message||'Delete failed.');}};
 const items=data?.items||[];
 return <><Helmet><title>Departures · Brother Tours Operations</title><meta name="robots" content="noindex,nofollow"/></Helmet><div className="space-y-5"><div className="flex items-start justify-between gap-3"><div><h1 className="text-xl font-semibold">Departures</h1><p className="mt-1 text-sm text-muted-foreground">Manage dates, seat capacity and availability status.</p></div><Button onClick={()=>open()}><Plus className="mr-1 h-4 w-4"/>New departure</Button></div><div className="grid gap-3 rounded-xl border border-border bg-card p-4 md:grid-cols-2 xl:grid-cols-5"><select className="h-10 rounded-lg border border-input bg-background px-3 text-sm" value={filters.tourId} onChange={e=>setFilters(f=>({...f,tourId:e.target.value,page:1}))}><option value="">All tours</option>{tours.map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select><select className="h-10 rounded-lg border border-input bg-background px-3 text-sm" value={filters.status} onChange={e=>setFilters(f=>({...f,status:e.target.value,page:1}))}><option value="">All statuses</option><option value="open">Open</option><option value="limited">Limited</option><option value="closed">Closed</option></select><Input type="date" value={filters.from} onChange={e=>setFilters(f=>({...f,from:e.target.value,page:1}))}/><Input type="date" value={filters.to} onChange={e=>setFilters(f=>({...f,to:e.target.value,page:1}))}/><button onClick={()=>setFilters(f=>({...f,status:'',tourId:'',from:'',to:'',page:1}))} className="h-10 rounded-lg border border-border px-3 text-sm">Clear filters</button></div>
 {state==='LOADING'&&<div className="space-y-2">{Array.from({length:7}).map((_,i)=><Skeleton key={i} className="h-16 rounded-lg"/>)}</div>}{state==='UNAVAILABLE'&&<UnavailableState error={error} onRetry={load}/>} {state==='ERROR'&&<ErrorState error={error} onRetry={load}/>} {state==='EMPTY'&&<EmptyState title="No departures found" description="Create a departure or adjust your filters."/>}
 {state==='DATA'&&<><div className="hidden overflow-x-auto rounded-xl border border-border bg-card md:block"><table className="w-full min-w-[760px] text-sm"><thead><tr className="border-b border-border bg-secondary/40 text-left text-xs text-muted-foreground"><th className="px-4 py-3">Date</th><th className="px-3 py-3">Tour</th><th className="px-3 py-3">Capacity</th><th className="px-3 py-3">Seats left</th><th className="px-3 py-3">Status</th><th className="px-3 py-3">Actions</th></tr></thead><tbody className="divide-y divide-border">{items.map(item=><tr key={item.id}><td className="px-4 py-3 font-medium">{formatDate(item.date,{month:'short',day:'numeric',year:'numeric'})}</td><td className="px-3 py-3">{item.tour}</td><td className="px-3 py-3">{item.seatsTotal}</td><td className="px-3 py-3">{item.seatsLeft}</td><td className="px-3 py-3"><InquiryStatusBadge status={item.status}/></td><td className="px-3 py-3"><div className="flex gap-1"><Button variant="ghost" size="sm" onClick={()=>open(item)}><Pencil className="mr-1 h-4 w-4"/>Edit</Button><Button variant="ghost" size="sm" className="text-destructive" onClick={()=>remove(item)}><Trash2 className="h-4 w-4"/></Button></div></td></tr>)}</tbody></table></div><div className="space-y-3 md:hidden">{items.map(item=><div key={item.id} className="rounded-xl border border-border bg-card p-4"><div className="flex items-start justify-between gap-2"><div><p className="font-semibold">{item.tour}</p><p className="mt-1 text-sm text-muted-foreground">{formatDate(item.date)}</p></div><InquiryStatusBadge status={item.status}/></div><div className="mt-3 flex items-center justify-between text-sm"><span>{item.seatsLeft} / {item.seatsTotal} seats left</span><div className="flex gap-1"><Button variant="ghost" size="sm" onClick={()=>open(item)}>Edit</Button><Button variant="ghost" size="sm" className="text-destructive" onClick={()=>remove(item)}>Delete</Button></div></div></div>)}</div></>}
 </div><Editor open={Boolean(editor)} onOpenChange={o=>!o&&setEditor(null)} form={form} setForm={setForm} tours={tours} saving={saving} error={formError} onSave={save} editing={Boolean(editor?.id)}/></>;
}
function Editor({open,onOpenChange,form,setForm,tours,saving,error,onSave,editing}){const set=(k,v)=>setForm(f=>({...f,[k]:v}));return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-w-xl"><DialogHeader><DialogTitle>{editing?'Edit departure':'New departure'}</DialogTitle><DialogDescription>Capacity and status are saved to the existing WPistic departure record.</DialogDescription></DialogHeader><div className="grid gap-4 sm:grid-cols-2"><label className="grid gap-2 text-xs text-muted-foreground sm:col-span-2">Tour<select className="h-10 rounded-lg border border-input bg-background px-3 text-sm text-foreground" value={form.tourId} onChange={e=>set('tourId',e.target.value)}><option value="">Select tour</option>{tours.map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select></label><label className="grid gap-2 text-xs text-muted-foreground">Departure date<Input type="date" value={form.date} onChange={e=>set('date',e.target.value)}/></label><label className="grid gap-2 text-xs text-muted-foreground">Status<select className="h-10 rounded-lg border border-input bg-background px-3 text-sm text-foreground" value={form.status} onChange={e=>set('status',e.target.value)}><option value="open">Open</option><option value="limited">Limited</option><option value="closed">Closed</option></select></label><label className="grid gap-2 text-xs text-muted-foreground">Total seats<Input type="number" min="0" value={form.seatsTotal} onChange={e=>set('seatsTotal',e.target.value)}/></label><label className="grid gap-2 text-xs text-muted-foreground">Seats left<Input type="number" min="0" value={form.seatsLeft} onChange={e=>set('seatsLeft',e.target.value)}/></label><label className="grid gap-2 text-xs text-muted-foreground sm:col-span-2">Optional title<Input value={form.title} onChange={e=>set('title',e.target.value)}/></label>{error&&<p className="sm:col-span-2 text-sm text-destructive">{error}</p>}</div><DialogFooter><Button variant="outline" onClick={()=>onOpenChange(false)}>Cancel</Button><Button disabled={saving} onClick={onSave}>{saving?'Saving…':'Save departure'}</Button></DialogFooter></DialogContent></Dialog>}
