import React,{useCallback,useEffect,useState} from 'react';
import {Helmet} from 'react-helmet';
import {Pencil,Plus,Search,Trash2} from 'lucide-react';
import {createExperience,deleteExperience,listDestinations,listExperiences,updateExperience} from '@/api/catalog';
import {ApiError} from '@/api/client';
import {EmptyState,ErrorState,Skeleton,UnavailableState} from '@/components/states/StateViews';
import {Dialog,DialogContent,DialogDescription,DialogFooter,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import TourStatusBadge from '@/components/tours/TourStatusBadge';

const blank={title:'',slug:'',status:'draft',excerpt:'',content:'',destinationId:0,bestSeason:'',featuredMedia:0};
export default function ExperiencesPage(){
 const [search,setSearch]=useState('');const [destinationId,setDestinationId]=useState('');const [state,setState]=useState('LOADING');const [data,setData]=useState(null);const [destinations,setDestinations]=useState([]);const [error,setError]=useState(null);const [editor,setEditor]=useState(null);const [form,setForm]=useState(blank);const [saving,setSaving]=useState(false);const [formError,setFormError]=useState('');
 const load=useCallback(async()=>{setState('LOADING');setError(null);try{const [r,d]=await Promise.all([listExperiences({perPage:100,search,destinationId}),listDestinations({perPage:100}).catch(()=>({items:[]}))]);setData(r);setDestinations(d.items||[]);setState((r?.items||[]).length?'DATA':'EMPTY');}catch(err){setError(err);setState(err instanceof ApiError&&err.isUnavailable?'UNAVAILABLE':'ERROR');}},[search,destinationId]);useEffect(()=>{load();},[load]);
 const open=(item=null)=>{setEditor(item||{});setForm(item?{title:item.title||'',slug:item.slug||'',status:item.status||'draft',excerpt:item.excerpt||'',content:item.content||'',destinationId:item.destinationId||0,bestSeason:item.bestSeason||'',featuredMedia:item.featuredMedia||0}:blank);setFormError('');};
 const save=async()=>{if(!form.title.trim()){setFormError('Title is required.');return;}setSaving(true);setFormError('');const payload={...form,destinationId:Number(form.destinationId)||0,featuredMedia:Number(form.featuredMedia)||0};try{editor?.id?await updateExperience(editor.id,payload):await createExperience(payload);setEditor(null);await load();}catch(err){setFormError(err?.message||'Save failed.');}finally{setSaving(false);}};
 const remove=async(item)=>{if(!window.confirm(`Move “${item.title}” to Trash?`))return;try{await deleteExperience(item.id);await load();}catch(err){window.alert(err?.message||'Delete failed.');}};
 return <><Helmet><title>Experiences · Brother Tours Operations</title><meta name="robots" content="noindex,nofollow"/></Helmet><div className="space-y-5"><div className="flex items-start justify-between gap-3"><div><h1 className="text-xl font-semibold">Experiences</h1><p className="mt-1 text-sm text-muted-foreground">Manage destination experiences and season information.</p></div><Button onClick={()=>open()}><Plus className="mr-1 h-4 w-4"/>New experience</Button></div><div className="grid gap-3 md:grid-cols-[1fr_240px]"><label className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground"/><Input className="pl-9" placeholder="Search experiences" value={search} onChange={e=>setSearch(e.target.value)}/></label><select className="h-10 rounded-lg border border-input bg-background px-3 text-sm" value={destinationId} onChange={e=>setDestinationId(e.target.value)}><option value="">All destinations</option>{destinations.map(d=><option key={d.id} value={d.id}>{d.title}</option>)}</select></div>
 {state==='LOADING'&&<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{Array.from({length:6}).map((_,i)=><Skeleton key={i} className="h-52 rounded-xl"/>)}</div>}{state==='UNAVAILABLE'&&<UnavailableState error={error} onRetry={load}/>} {state==='ERROR'&&<ErrorState error={error} onRetry={load}/>} {state==='EMPTY'&&<EmptyState title="No experiences found" description="Create an experience or adjust your filters."/>}
 {state==='DATA'&&<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{data.items.map(item=><div key={item.id} className="overflow-hidden rounded-xl border border-border bg-card"><div className="aspect-[16/8] bg-secondary">{item.featuredImage?<img src={item.featuredImage} alt="" className="h-full w-full object-cover"/>:<div className="flex h-full items-center justify-center text-sm text-muted-foreground">No image</div>}</div><div className="p-4"><div className="flex items-start justify-between gap-3"><h2 className="font-semibold">{item.title}</h2><TourStatusBadge status={item.status}/></div><p className="mt-2 text-sm text-muted-foreground">{item.destination||'No destination'}{item.bestSeason?` · ${item.bestSeason}`:''}</p><div className="mt-4 flex gap-2"><Button variant="outline" size="sm" onClick={()=>open(item)}><Pencil className="mr-1 h-4 w-4"/>Edit</Button><Button variant="outline" size="sm" className="text-destructive" onClick={()=>remove(item)}><Trash2 className="mr-1 h-4 w-4"/>Trash</Button></div></div></div>)}</div>}
 </div><Editor open={Boolean(editor)} onOpenChange={o=>!o&&setEditor(null)} title={editor?.id?'Edit experience':'New experience'} form={form} setForm={setForm} destinations={destinations} saving={saving} error={formError} onSave={save}/></>;
}
function Editor({open,onOpenChange,title,form,setForm,destinations,saving,error,onSave}){const set=(k,v)=>setForm(f=>({...f,[k]:v}));return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[90vh] max-w-2xl overflow-y-auto"><DialogHeader><DialogTitle>{title}</DialogTitle><DialogDescription>Saved directly to the existing WordPress experience record.</DialogDescription></DialogHeader><div className="grid gap-4"><Field label="Title" value={form.title} onChange={v=>set('title',v)}/><div className="grid gap-4 sm:grid-cols-2"><Field label="Slug" value={form.slug} onChange={v=>set('slug',v)}/><label className="grid gap-2 text-xs text-muted-foreground">Status<select className="h-10 rounded-lg border border-input bg-background px-3 text-sm text-foreground" value={form.status} onChange={e=>set('status',e.target.value)}>{['draft','publish','pending','private'].map(v=><option key={v} value={v}>{v==='publish'?'Published':v}</option>)}</select></label><label className="grid gap-2 text-xs text-muted-foreground">Destination<select className="h-10 rounded-lg border border-input bg-background px-3 text-sm text-foreground" value={form.destinationId} onChange={e=>set('destinationId',e.target.value)}><option value="0">None</option>{destinations.map(d=><option key={d.id} value={d.id}>{d.title}</option>)}</select></label><Field label="Best season" value={form.bestSeason} onChange={v=>set('bestSeason',v)}/><Field label="Featured media attachment ID" type="number" value={form.featuredMedia} onChange={v=>set('featuredMedia',v)}/></div><Area label="Excerpt" value={form.excerpt} onChange={v=>set('excerpt',v)}/><Area label="Content" rows={8} value={form.content} onChange={v=>set('content',v)}/>{error&&<p className="text-sm text-destructive">{error}</p>}</div><DialogFooter><Button variant="outline" onClick={()=>onOpenChange(false)}>Cancel</Button><Button disabled={saving} onClick={onSave}>{saving?'Saving…':'Save experience'}</Button></DialogFooter></DialogContent></Dialog>}
function Field({label,value,onChange,type='text'}){return <label className="grid gap-2 text-xs text-muted-foreground">{label}<Input type={type} className="text-foreground" value={value??''} onChange={e=>onChange(e.target.value)}/></label>}
function Area({label,value,onChange,rows=4}){return <label className="grid gap-2 text-xs text-muted-foreground">{label}<Textarea rows={rows} className="text-foreground" value={value??''} onChange={e=>onChange(e.target.value)}/></label>}
