import React,{useCallback,useEffect,useState} from 'react';
import {Helmet} from 'react-helmet';
import {useNavigate} from 'react-router-dom';
import {ChevronLeft,ChevronRight,Mail,Search} from 'lucide-react';
import {fetchInboxStats,listSubmissions} from '@/api/inbox';
import {ApiError} from '@/api/client';
import {EmptyState,ErrorState,Skeleton,UnavailableState} from '@/components/states/StateViews';
import InquiryStatusBadge from '@/components/inquiries/InquiryStatusBadge';
import {MetricCard} from '@/components/dashboard/MetricCard';
import {formatDate,formatNumber} from '@/lib/format';

export default function InboxPage(){
 const [filters,setFilters]=useState({page:1,perPage:20,search:'',status:'',formName:'',from:'',to:''});const [state,setState]=useState('LOADING');const [data,setData]=useState(null);const [stats,setStats]=useState(null);const [error,setError]=useState(null);const navigate=useNavigate();
 const load=useCallback(async()=>{setState('LOADING');setError(null);try{const [r,s]=await Promise.all([listSubmissions(filters),fetchInboxStats().catch(()=>null)]);setData(r);setStats(s);setState((r?.items||[]).length?'DATA':'EMPTY');}catch(err){setError(err);setState(err instanceof ApiError&&err.isUnavailable?'UNAVAILABLE':'ERROR');}},[filters]);useEffect(()=>{load();},[load]);
 const items=data?.items||[];const pages=data?.totalPages||1;
 return <><Helmet><title>Form Inbox · Brother Tours Operations</title><meta name="robots" content="noindex,nofollow"/></Helmet><div className="space-y-5"><div><h1 className="text-xl font-semibold">Form Inbox</h1><p className="mt-1 text-sm text-muted-foreground">Review Formistic submissions, replies, notes and AI metadata.</p></div>
 {stats&&<div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><MetricCard label="Today" value={formatNumber(stats.today)} icon={Mail}/><MetricCard label="Last 7 days" value={formatNumber(stats.last7Days)} icon={Mail}/><MetricCard label="Overdue 24h" value={formatNumber(stats.overdue24h)} icon={Mail}/><MetricCard label="Reply rate" value={`${Number(stats.repliedRate||0).toFixed(1)}%`} icon={Mail}/></div>}
 <div className="grid gap-3 rounded-xl border border-border bg-card p-4 md:grid-cols-2 xl:grid-cols-5"><label className="relative xl:col-span-2"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground"/><input className="h-10 w-full rounded-lg border border-input bg-background pl-9 pr-3 text-sm" placeholder="Search name, email or message" value={filters.search} onChange={e=>setFilters(f=>({...f,search:e.target.value,page:1}))}/></label><select className="h-10 rounded-lg border border-input bg-background px-3 text-sm" value={filters.status} onChange={e=>setFilters(f=>({...f,status:e.target.value,page:1}))}><option value="">All statuses</option><option value="new">New</option><option value="read">Read</option><option value="replied">Replied</option></select><input className="h-10 rounded-lg border border-input bg-background px-3 text-sm" placeholder="Form name" value={filters.formName} onChange={e=>setFilters(f=>({...f,formName:e.target.value,page:1}))}/><div className="grid grid-cols-2 gap-2"><input className="h-10 rounded-lg border border-input bg-background px-2 text-sm" type="date" value={filters.from} onChange={e=>setFilters(f=>({...f,from:e.target.value,page:1}))}/><input className="h-10 rounded-lg border border-input bg-background px-2 text-sm" type="date" value={filters.to} onChange={e=>setFilters(f=>({...f,to:e.target.value,page:1}))}/></div></div>
 {state==='LOADING'&&<div className="space-y-2">{Array.from({length:8}).map((_,i)=><Skeleton key={i} className="h-16 rounded-lg"/>)}</div>}{state==='UNAVAILABLE'&&<UnavailableState error={error} onRetry={load}/>} {state==='ERROR'&&<ErrorState error={error} onRetry={load}/>} {state==='EMPTY'&&<EmptyState title="No form submissions" description="No submissions match the current filters."/>}
 {state==='DATA'&&<><div className="overflow-hidden rounded-xl border border-border bg-card"><div className="divide-y divide-border">{items.map(item=><button key={item.id} onClick={()=>navigate(`/inbox/${item.id}`)} className="grid w-full gap-2 p-4 text-left transition hover:bg-secondary/30 md:grid-cols-[1.1fr_1.6fr_150px_130px]"><div className="min-w-0"><p className="truncate text-sm font-medium">{item.senderName||item.senderEmail||'Unknown sender'}</p><p className="truncate text-xs text-muted-foreground">{item.senderEmail||item.senderPhone}</p></div><div className="min-w-0"><p className="truncate text-sm">{item.subject||item.formName||'Submission'}</p><p className="mt-1 line-clamp-1 text-xs text-muted-foreground">{item.message||'No message'}</p></div><div><InquiryStatusBadge status={item.status}/></div><div className="text-xs text-muted-foreground">{formatDate(item.createdAt,{month:'short',day:'numeric',year:'numeric'})}</div></button>)}</div></div><div className="flex items-center justify-between"><p className="text-sm text-muted-foreground">{data.total||items.length} submissions · Page {filters.page} of {pages}</p><div className="flex gap-2"><button disabled={filters.page<=1} onClick={()=>setFilters(f=>({...f,page:f.page-1}))} className="inline-flex h-9 items-center gap-1 rounded-lg border border-border px-3 text-sm disabled:opacity-40"><ChevronLeft className="h-4 w-4"/>Previous</button><button disabled={filters.page>=pages} onClick={()=>setFilters(f=>({...f,page:f.page+1}))} className="inline-flex h-9 items-center gap-1 rounded-lg border border-border px-3 text-sm disabled:opacity-40">Next<ChevronRight className="h-4 w-4"/></button></div></div></>}
 </div></>;
}
