import React,{useCallback,useEffect,useState} from 'react';
import {Helmet} from 'react-helmet-async';
import {Link,useParams} from 'react-router-dom';
import {ArrowLeft,Paperclip,RefreshCw,Send} from 'lucide-react';
import {addSubmissionNote,getSubmission,replyToSubmission,setSubmissionStatus} from '@/api/inbox';
import {ApiError} from '@/api/client';
import {EmptyState,ErrorState,SkeletonPanel,UnavailableState} from '@/components/states/StateViews';
import InquiryStatusBadge from '@/components/inquiries/InquiryStatusBadge';
import {formatDate} from '@/lib/format';

export default function SubmissionDetailPage(){
 const {id}=useParams();const [state,setState]=useState('LOADING');const [data,setData]=useState(null);const [error,setError]=useState(null);const [working,setWorking]=useState(false);const [notice,setNotice]=useState('');const [actionError,setActionError]=useState('');const [note,setNote]=useState('');const [tags,setTags]=useState('');const [reply,setReply]=useState({subject:'',body:'',cc:'',bcc:'',html:false});
 const load=useCallback(async()=>{setState('LOADING');setError(null);try{const r=await getSubmission(id);setData(r);setReply(x=>({...x,subject:x.subject||`Re: ${r.subject||r.formName||'Your enquiry'}`}));setState(r?'DATA':'EMPTY');}catch(err){setError(err);setState(err instanceof ApiError&&err.isUnavailable?'UNAVAILABLE':'ERROR');}},[id]);useEffect(()=>{load();},[load]);
 const run=async(fn,msg)=>{setWorking(true);setNotice('');setActionError('');try{await fn();setNotice(msg);await load();return true;}catch(err){setActionError(err?.message||'Action failed.');return false;}finally{setWorking(false);}};
 if(state==='LOADING')return <SkeletonPanel rows={10}/>;if(state==='UNAVAILABLE')return <UnavailableState error={error} onRetry={load}/>;if(state==='ERROR')return <ErrorState error={error} onRetry={load}/>;if(state==='EMPTY'||!data)return <EmptyState title="Submission not found"/>;
 return <><Helmet><title>{data.subject||data.formName||'Submission'} · Brother Tours Operations</title><meta name="robots" content="noindex,nofollow"/></Helmet><div className="space-y-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><Link to="/inbox" className="inline-flex items-center gap-1 text-sm text-muted-foreground"><ArrowLeft className="h-4 w-4"/>Form Inbox</Link><div className="mt-3 flex items-center gap-2"><h1 className="text-xl font-semibold">{data.subject||data.formName||'Form submission'}</h1><InquiryStatusBadge status={data.status}/></div><p className="mt-1 text-sm text-muted-foreground">{data.senderName||'Unknown sender'} · {data.senderEmail||''}</p></div><button onClick={load} className="inline-flex h-9 items-center gap-2 rounded-lg border border-border px-3 text-sm"><RefreshCw className="h-4 w-4"/>Refresh</button></div>{notice&&<div className="rounded-lg border border-emerald-500/30 bg-emerald-500/10 px-3 py-2 text-sm text-emerald-700 dark:text-emerald-400">{notice}</div>}{actionError&&<div className="rounded-lg border border-destructive/30 bg-destructive/10 px-3 py-2 text-sm text-destructive">{actionError}</div>}
 <div className="grid gap-5 xl:grid-cols-[1fr_360px]"><div className="space-y-5"><Panel title="Message"><div className="grid gap-4 sm:grid-cols-2"><Info label="Form" value={data.formName}/><Info label="Received" value={formatDate(data.createdAt)}/><Info label="Email" value={data.senderEmail}/><Info label="Phone" value={data.senderPhone}/></div><p className="mt-5 whitespace-pre-line text-sm leading-relaxed">{data.message||'No message body.'}</p>{Object.keys(data.fields||{}).length>0&&<div className="mt-5 border-t border-border pt-4"><p className="mb-3 text-xs font-semibold uppercase tracking-wide text-muted-foreground">Submitted fields</p><dl className="grid gap-3 sm:grid-cols-2">{Object.entries(data.fields).map(([k,v])=><div key={k}><dt className="text-xs text-muted-foreground">{k}</dt><dd className="mt-1 break-words text-sm">{Array.isArray(v)?v.join(', '):String(v??'')}</dd></div>)}</dl></div>}</Panel>
 <Panel title="Conversation">{(data.replies||[]).length===0?<p className="text-sm text-muted-foreground">No replies sent yet.</p>:<div className="space-y-3">{data.replies.map(r=><div key={r.id} className="rounded-lg border border-border p-3"><div className="flex items-center justify-between gap-3"><p className="text-sm font-medium">{r.subject}</p><span className="text-xs text-muted-foreground">{formatDate(r.sentAt)}</span></div><p className="mt-2 whitespace-pre-line text-sm text-muted-foreground">{stripHtml(r.body)}</p></div>)}</div>}</Panel>
 <Panel title="Internal notes">{(data.notes||[]).length===0?<p className="text-sm text-muted-foreground">No notes yet.</p>:<div className="space-y-3">{data.notes.map(n=><div key={n.id} className="rounded-lg border border-border p-3"><p className="whitespace-pre-line text-sm">{n.body}</p><p className="mt-2 text-xs text-muted-foreground">{n.author||`User ${n.createdBy}`} · {formatDate(n.createdAt)}{n.tags?` · ${n.tags}`:''}</p></div>)}</div>}</Panel>
 <Panel title="Attachments">{(data.attachments||[]).length===0?<p className="text-sm text-muted-foreground">No attachments.</p>:<div className="space-y-2">{data.attachments.map(a=><div key={a.id} className="flex items-center gap-3 rounded-lg border border-border p-3"><Paperclip className="h-4 w-4"/><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{a.name}</p><p className="text-xs text-muted-foreground">{a.mimeType} · {formatBytes(a.sizeBytes)}</p></div>{a.externalUrl&&<a href={a.externalUrl} target="_blank" rel="noreferrer" className="text-xs font-medium text-primary">Open</a>}</div>)}</div>}</Panel>
 {data.aiMeta&&<Panel title="AI metadata"><Info label="Spam score" value={data.aiMeta.spamScore}/><p className="mt-3 text-sm"><span className="text-muted-foreground">Tags:</span> {data.aiMeta.tags||'—'}</p>{data.aiMeta.reply&&<div className="mt-4 rounded-lg bg-secondary/40 p-3"><p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">Suggested reply</p><p className="mt-2 whitespace-pre-line text-sm">{data.aiMeta.reply}</p><button onClick={()=>setReply(r=>({...r,body:data.aiMeta.reply}))} className="mt-3 text-xs font-medium text-primary">Use as draft</button></div>}</Panel>}
 </div><aside className="space-y-5"><Panel title="Status"><select className="h-10 w-full rounded-lg border border-input bg-background px-3 text-sm" value={data.status} disabled={working} onChange={e=>run(()=>setSubmissionStatus(id,e.target.value),'Status updated.')}><option value="new">New</option><option value="read">Read</option><option value="replied">Replied</option></select></Panel><Panel title="Add note"><textarea className="min-h-24 w-full rounded-lg border border-input bg-background p-3 text-sm" placeholder="Internal note" value={note} onChange={e=>setNote(e.target.value)}/><input className="mt-2 h-9 w-full rounded-lg border border-input bg-background px-3 text-sm" placeholder="Tags (optional)" value={tags} onChange={e=>setTags(e.target.value)}/><button disabled={working||!note.trim()} onClick={async()=>{if(await run(()=>addSubmissionNote(id,note,tags),'Note saved.')){setNote('');setTags('');}}} className="mt-2 h-9 w-full rounded-lg bg-primary text-sm font-semibold text-primary-foreground disabled:opacity-50">Save note</button></Panel><Panel title="Reply"><input className="h-10 w-full rounded-lg border border-input bg-background px-3 text-sm" placeholder="Subject" value={reply.subject} onChange={e=>setReply(r=>({...r,subject:e.target.value}))}/><textarea className="mt-2 min-h-40 w-full rounded-lg border border-input bg-background p-3 text-sm" placeholder="Reply message" value={reply.body} onChange={e=>setReply(r=>({...r,body:e.target.value}))}/><input className="mt-2 h-9 w-full rounded-lg border border-input bg-background px-3 text-sm" placeholder="Cc addresses, comma separated" value={reply.cc} onChange={e=>setReply(r=>({...r,cc:e.target.value}))}/><input className="mt-2 h-9 w-full rounded-lg border border-input bg-background px-3 text-sm" placeholder="Bcc addresses, comma separated" value={reply.bcc} onChange={e=>setReply(r=>({...r,bcc:e.target.value}))}/><button disabled={working||!reply.subject.trim()||!reply.body.trim()} onClick={async()=>{if(!window.confirm(`Send this reply to ${data.senderEmail}?`))return;if(await run(()=>replyToSubmission(id,reply),'Reply sent.'))setReply(r=>({...r,body:''}));}} className="mt-2 inline-flex h-9 w-full items-center justify-center gap-2 rounded-lg bg-primary text-sm font-semibold text-primary-foreground disabled:opacity-50"><Send className="h-4 w-4"/>Send reply</button></Panel></aside></div>
 </div></>;
}
function Panel({title,children}){return <section className="rounded-xl border border-border bg-card p-5"><h2 className="mb-4 text-xs font-semibold uppercase tracking-[0.13em] text-muted-foreground">{title}</h2>{children}</section>}
function Info({label,value}){return <div><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 break-words text-sm font-medium">{value||'—'}</p></div>}
function stripHtml(v){return String(v||'').replace(/<br\s*\/?>/gi,'\n').replace(/<[^>]+>/g,'').replace(/&nbsp;/g,' ').trim()}
function formatBytes(n){const v=Number(n)||0;if(v<1024)return `${v} B`;if(v<1024*1024)return `${(v/1024).toFixed(1)} KB`;return `${(v/1024/1024).toFixed(1)} MB`}
