import React, { useCallback, useEffect, useState } from 'react';
import { Helmet } from 'react-helmet';
import { useNavigate } from 'react-router-dom';
import { ChevronLeft, ChevronRight, Plus, Search } from 'lucide-react';
import { fetchTours } from '@/api/tours';
import { ApiError } from '@/api/client';
import { EmptyState, ErrorState, Skeleton, UnavailableState } from '@/components/states/StateViews';
import TourStatusBadge from '@/components/tours/TourStatusBadge';
import { formatDate } from '@/lib/format';

export default function ToursPage(){
  const [filters,setFilters]=useState({page:1,perPage:20,search:'',status:'',orderby:'modified',order:'DESC'}); const [state,setState]=useState('LOADING'); const [result,setResult]=useState(null); const [error,setError]=useState(null); const navigate=useNavigate();
  const load=useCallback(async()=>{setState('LOADING');setError(null);try{const r=await fetchTours(filters);setResult(r);setState((r?.items||[]).length?'DATA':'EMPTY');}catch(err){setError(err);setState(err instanceof ApiError&&err.isUnavailable?'UNAVAILABLE':'ERROR');}},[filters]);
  useEffect(()=>{load();},[load]); const items=result?.items||[]; const pages=result?.totalPages||1;
  return <><Helmet><title>Tours · Brother Tours Operations</title><meta name="robots" content="noindex,nofollow"/></Helmet><div className="space-y-5">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-xl font-semibold">Tours</h1><p className="mt-1 text-sm text-muted-foreground">Manage Brother Tours products and WPistic tour metadata.</p></div><button onClick={()=>navigate('/tours/new')} className="inline-flex h-9 items-center gap-2 rounded-lg bg-primary px-3 text-sm font-semibold text-primary-foreground"><Plus className="h-4 w-4"/>New tour</button></div>
    <div className="grid gap-3 rounded-xl border border-border bg-card p-4 md:grid-cols-[1fr_180px_180px]"><label className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground"/><input className="h-10 w-full rounded-lg border border-input bg-background pl-9 pr-3 text-sm" placeholder="Search tours" value={filters.search} onChange={e=>setFilters(f=>({...f,search:e.target.value,page:1}))}/></label><select className="h-10 rounded-lg border border-input bg-background px-3 text-sm" value={filters.status} onChange={e=>setFilters(f=>({...f,status:e.target.value,page:1}))}><option value="">All statuses</option>{['publish','draft','pending','private','future','trash'].map(v=><option key={v} value={v}>{v==='publish'?'Published':cap(v)}</option>)}</select><select className="h-10 rounded-lg border border-input bg-background px-3 text-sm" value={`${filters.orderby}:${filters.order}`} onChange={e=>{const [orderby,order]=e.target.value.split(':');setFilters(f=>({...f,orderby,order,page:1}));}}><option value="modified:DESC">Recently updated</option><option value="date:DESC">Newest created</option><option value="title:ASC">Title A–Z</option><option value="ID:DESC">Newest ID</option></select></div>
    {state==='LOADING'&&<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{Array.from({length:6}).map((_,i)=><Skeleton key={i} className="h-60 rounded-xl"/>)}</div>}{state==='UNAVAILABLE'&&<UnavailableState error={error} onRetry={load}/>} {state==='ERROR'&&<ErrorState error={error} onRetry={load}/>} {state==='EMPTY'&&<EmptyState title="No tours found" description="Create a tour or adjust the filters."/>}
    {state==='DATA'&&<><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{items.map(t=><button key={t.id} onClick={()=>navigate(`/tours/${t.id}`)} className="overflow-hidden rounded-xl border border-border bg-card text-left transition hover:border-primary/40"><div className="aspect-[16/8] bg-secondary">{t.featuredImage?<img src={t.featuredImage} alt="" className="h-full w-full object-cover"/>:<div className="flex h-full items-center justify-center text-sm text-muted-foreground">No featured image</div>}</div><div className="p-4"><div className="flex items-start justify-between gap-3"><h2 className="font-semibold">{t.title}</h2><TourStatusBadge status={t.status}/></div><p className="mt-2 line-clamp-2 text-sm text-muted-foreground">{t.meta?.wpistic_short_summary||t.excerpt||'No summary'}</p><div className="mt-3 flex items-center justify-between text-xs text-muted-foreground"><span>{t.meta?.wpistic_duration||'Duration not set'}</span><span>{formatDate(t.modifiedAt,{month:'short',day:'numeric',year:'numeric'})}</span></div></div></button>)}</div><div className="flex items-center justify-between"><p className="text-sm text-muted-foreground">{result?.total||items.length} tours · Page {filters.page} of {pages}</p><div className="flex gap-2"><button disabled={filters.page<=1} onClick={()=>setFilters(f=>({...f,page:f.page-1}))} className="inline-flex h-9 items-center gap-1 rounded-lg border border-border px-3 text-sm disabled:opacity-40"><ChevronLeft className="h-4 w-4"/>Previous</button><button disabled={filters.page>=pages} onClick={()=>setFilters(f=>({...f,page:f.page+1}))} className="inline-flex h-9 items-center gap-1 rounded-lg border border-border px-3 text-sm disabled:opacity-40">Next<ChevronRight className="h-4 w-4"/></button></div></div></>}
  </div></>;
}
function cap(v){return String(v||'').replace(/_/g,' ').replace(/\b\w/g,m=>m.toUpperCase())}
