import React, { useCallback, useEffect, useState } from 'react';
import { Helmet } from 'react-helmet-async';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { ArrowLeft, ExternalLink, Pencil, RefreshCw } from 'lucide-react';
import { createTour, deleteTour, fetchTour, updateTour } from '@/api/tours';
import { ApiError } from '@/api/client';
import { EmptyState, ErrorState, SkeletonPanel, UnavailableState } from '@/components/states/StateViews';
import TourEditor from '@/components/tours/TourEditor';
import TourStatusBadge from '@/components/tours/TourStatusBadge';
import { formatDate } from '@/lib/format';

export default function TourDetailPage({ mode = 'view' }) {
  const { id } = useParams(); const navigate = useNavigate(); const create = mode === 'create'; const [state, setState] = useState(create ? 'DATA' : 'LOADING'); const [tour, setTour] = useState(create ? {} : null); const [error, setError] = useState(null); const [editing, setEditing] = useState(create); const [saving, setSaving] = useState(false); const [saveError, setSaveError] = useState(null); const [notice, setNotice] = useState('');
  const load = useCallback(async () => { if (create) return; setState('LOADING'); setError(null); try { const r = await fetchTour(id); setTour(r); setState(r ? 'DATA' : 'EMPTY'); } catch (err) { setError(err); setState(err instanceof ApiError && err.isUnavailable ? 'UNAVAILABLE' : 'ERROR'); } }, [id, create]);
  useEffect(() => { load(); }, [load]);
  const save = async (payload) => { setSaving(true); setSaveError(null); try { const r = create ? await createTour(payload) : await updateTour(id, payload); setTour(r); setNotice(create ? 'Tour created.' : 'Tour updated.'); if (create && r?.id) { navigate(`/tours/${r.id}`, { replace: true }); return; } setEditing(false); } catch (err) { setSaveError(err); } finally { setSaving(false); } };
  const remove = async () => { if (!window.confirm('Move this tour to Trash?')) return; setSaving(true); try { await deleteTour(id); navigate('/tours', { replace: true }); } catch (err) { setSaveError(err); setSaving(false); } };
  if (state === 'LOADING') return <SkeletonPanel rows={10} />; if (state === 'UNAVAILABLE') return <UnavailableState error={error} onRetry={load} />; if (state === 'ERROR') return <ErrorState error={error} onRetry={load} />; if (state === 'EMPTY') return <EmptyState title="Tour not found" />;
  if (editing) return <><Helmet><title>{create ? 'New tour' : `Edit ${tour?.title || 'tour'}`} · Brother Tours Operations</title><meta name="robots" content="noindex,nofollow" /></Helmet><div className="mb-4"><Link to="/tours" className="inline-flex items-center gap-1 text-sm text-muted-foreground"><ArrowLeft className="h-4 w-4" />Tours</Link></div><TourEditor tour={tour} mode={create ? 'create' : 'edit'} saving={saving} saveError={saveError} onSave={save} onCancel={() => create ? navigate('/tours') : setEditing(false)} onDelete={create ? null : remove} /></>;
  const m = tour?.meta || {};
  return <><Helmet><title>{tour?.title || 'Tour'} · Brother Tours Operations</title><meta name="robots" content="noindex,nofollow" /></Helmet><div className="space-y-5">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><Link to="/tours" className="inline-flex items-center gap-1 text-sm text-muted-foreground"><ArrowLeft className="h-4 w-4" />Tours</Link><div className="mt-3 flex items-center gap-2"><h1 className="text-xl font-semibold">{tour.title}</h1><TourStatusBadge status={tour.status} /></div><p className="mt-1 text-sm text-muted-foreground">{m.wpistic_subtitle || m.wpistic_short_summary || tour.excerpt}</p></div><div className="flex gap-2"><button onClick={load} className="inline-flex h-9 items-center gap-1.5 rounded-lg border border-border px-3 text-sm"><RefreshCw className="h-4 w-4" />Refresh</button>{tour.permalink && <a href={tour.permalink} target="_blank" rel="noreferrer" className="inline-flex h-9 items-center gap-1.5 rounded-lg border border-border px-3 text-sm">Preview<ExternalLink className="h-4 w-4" /></a>}<button onClick={() => setEditing(true)} className="inline-flex h-9 items-center gap-1.5 rounded-lg bg-primary px-3 text-sm font-semibold text-primary-foreground"><Pencil className="h-4 w-4" />Edit</button></div></div>
    {notice && <div className="rounded-lg border border-emerald-500/30 bg-emerald-500/10 px-3 py-2 text-sm text-emerald-700 dark:text-emerald-400">{notice}</div>}
    <div className="overflow-hidden rounded-xl border border-border bg-card">{tour.featuredImage && <img src={tour.featuredImage} alt="" className="h-60 w-full object-cover" />}<div className="p-5"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Info label="Duration" value={m.wpistic_duration} /><Info label="Start" value={m.wpistic_start_location} /><Info label="End" value={m.wpistic_end_location} /><Info label="From price" value={m.wpistic_from_price} /><Info label="Group size" value={m.wpistic_group_size} /><Info label="Minimum age" value={m.wpistic_minimum_age} /><Info label="Season" value={m.wpistic_season} /><Info label="Updated" value={formatDate(tour.modifiedAt)} /></div></div></div>
    <div className="grid gap-5 xl:grid-cols-2"><Panel title="Content"><p className="whitespace-pre-wrap text-sm leading-relaxed">{stripHtml(tour.content) || 'No main content.'}</p></Panel><Panel title="Pricing & operations"><InfoGrid items={[["Pricing type", m.wpistic_pricing_type], ["Deposit type", m.wpistic_deposit_type], ["Deposit value", m.wpistic_deposit_value], ["Deposit min", m.wpistic_deposit_min], ["Deposit max", m.wpistic_deposit_max], ["Accommodation", m.wpistic_accommodation], ["Transport", m.wpistic_transport], ["Availability", m.wpistic_availability]]} /></Panel></div>
    <Panel title="Itinerary">{(m.wpistic_itinerary || []).length ? <div className="space-y-4">{m.wpistic_itinerary.map((x, i) => <div key={i} className="border-l-2 border-primary/40 pl-4"><p className="font-medium">{x.title || `Item ${i + 1}`}</p><p className="mt-1 whitespace-pre-line text-sm text-muted-foreground">{x.body}</p></div>)}</div> : <p className="text-sm text-muted-foreground">No itinerary configured.</p>}</Panel>
    <div className="grid gap-5 xl:grid-cols-3"><Panel title="Inclusions"><List values={m.wpistic_inclusions} /></Panel><Panel title="Exclusions"><List values={m.wpistic_exclusions} /></Panel><Panel title="FAQ">{(m.wpistic_faq || []).length ? <div className="space-y-3">{m.wpistic_faq.map((x, i) => <div key={i}><p className="text-sm font-medium">{x.q}</p><p className="mt-1 text-sm text-muted-foreground">{x.a}</p></div>)}</div> : <p className="text-sm text-muted-foreground">No FAQ configured.</p>}</Panel></div>
  </div></>;
}
function Panel({ title, children }) { return <section className="rounded-xl border border-border bg-card p-5"><h2 className="mb-4 text-xs font-semibold uppercase tracking-[0.13em] text-muted-foreground">{title}</h2>{children}</section> }
function Info({ label, value }) { return <div><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-sm font-medium">{value || '—'}</p></div> }
function InfoGrid({ items }) { return <div className="grid gap-4 sm:grid-cols-2">{items.map(([k, v]) => <Info key={k} label={k} value={v} />)}</div> }
function List({ values = [] }) { return values.length ? <ul className="space-y-2">{values.map((v, i) => <li key={i} className="text-sm">• {v}</li>)}</ul> : <p className="text-sm text-muted-foreground">None configured.</p> }
function stripHtml(v) { return String(v || '').replace(/<[^>]+>/g, '').replace(/&nbsp;/g, ' ').trim() }
